## Composeファイルのバージョン
version: '3'

volumes:
  mysql-volume:

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src/:/var/www/html
 
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - app
    volumes:
      - ./src/:/var/www/html

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
      TZ: 'Asia/Tokyo'

    volumes:
      - mysql-volume:/var/lib/mysql
# ----------------------------------
# phpMyAdminを動かすコンテナ
# ----------------------------------
  phpmyadmin:
  # Docker Hubからイメージをダウンロード
    image: phpmyadmin/phpmyadmin:5

    # コンテナの名前
    container_name: phpmyadmin_laravel_crm

    # コンテナと他のサービスを繋げる
    links:
      - db

    # localhost:8080 で phpmyadmin の管理画面にアクセス
    ports:
     - 8080:80

    # セッション情報をボリュームに設定して永続化
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
  
  mysql-client:
    image: mysql:latest
    command: [mysql, "--version"]  # 任意のMySQLクライアントコマンドを実行して確認できます
    depends_on:
      - db
